title: Unimakers CDR 2024
description: Documentation de la réalisation des robots pour notre participation à la Coupe de France de Robotique 2024

# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Thème
remote_theme: pmarsceill/just-the-docs

# Paramètres optionnels de "Just the Docs"
just_the_docs:
  navigation_depth: 7
  search_enabled: true
  search_indexing: true

callouts:
  note:
    title: Note
    color: purple

# Plugins
plugins:
  - jekyll-remote-theme

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
